name: Comment NPM Publish
description: Put a comment in for an NPM publish operation
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  command:
    description: Comment on npm publish
    required: true
runs:
  using: node20
  pre: '../setup.mjs'
  main: ../dist-mjs/comment-npm-publish/index.mjs
