name: Comment NPM Publish
description: Put a comment in for an NPM publish operation
inputs:
  betaPackage:
    description: published beta package
    required: true
runs:
  using: node24
  pre: '../src/setup.ts'
  main: ../src/comment-npm-publish/index.ts
