name: Code Coverage Report
description: Comments a pull request with the code coverage
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  coverage-results-folder-pr:
    description: The test coverage results folder of PR branch
    required: true
  coverage-results-folder-base:
    description: The test coverage results folder of main branch
    required: true
  filter-changed-files:
    description: Set to true to only comment with coverage on files changed in this commit
    required: false
    default: 'false'
  delete-old-comments:
    description: Set to true to delete old Coverage Report comments
    required: false
    default: 'false'
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: './'
  title:
    description: Title to add to the comment
    required: false
runs:
  using: node24
  pre: '../src/setup.ts'
  main: ../src/coverage-reporter/index.ts
