name: Bundle
description: Bundle the project and validate the bundle and size
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  command:
    description: command to run
    required: true
runs:
  using: node20
  pre: '../setup.mjs'
  main: ../dist-mjs/perform-bundle/index.mjs
