name: Check Pull Request Reviews
description: Checks that a Pull request has been reviewed by all reviewers attached to the pull request
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  command:
    description: command to run
    required: true
runs:
  using: node16
  pre: '../setup.mjs'
  main: ../build/check-pr-reviews/index.js
