name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pullRequestBuild:
    name: Pull Request Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '21.x']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Compile
        run: npm run ci:compile
      - name: Check Code Style
        run: npm run ci:style
      - name: Perform Linting
        run: npm run ci:lint
      - name: Run Tests
        run: npm run ci:test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}

  branchBuild:
    name: Branch Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '21.x']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Compile
        run: npm run ci:compile
      - name: Check Code Style
        run: npm run ci:style
      - name: Perform Linting
        run: npm run ci:lint
      - name: Run Tests
        run: npm run ci:test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
